### Edit PORT number in this line 
@BASE_URL= http://localhost:3000

### Edit Authorization token in this line 
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNzZjMTQzLWI0ZTctNDUwZS05ZDQ5LTJjZWMwZmNhMGMyZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMTY2OTczMywiZXhwIjoxNzMxNjczMzMzfQ.iZ-3s1xwG8WBtBbIPn6F2GzgHJpmM1J358LcdyYRt74


### Edit userID in this line 
@USER_ID = a076c143-b4e7-450e-9d49-2cec0fca0c2e


### Edit postID in this line 
@POST_ID = 


### Register a new user
POST {{BASE_URL}}/users/register
Content-Type: application/json

{
  "name": "jaume",  
  "email": "jaume@email.com",
  "password": "jaume"
}


### Login a user to get a token
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
  "email": "jaume@email.com",
  "password": "jaume"
}


### Get all users (requires admin authentication)
GET {{BASE_URL}}/users
Authorization: Bearer {{TOKEN}}


### Soft delete a user by ID (requires authentication)
# Replace 'userId' with the actual user ID you want to delete
DELETE {{BASE_URL}}/users/{{USER_ID}}
Authorization: Bearer {{TOKEN}}


### Restore a user by ID (requires authentication)
# Replace 'userId' with the actual user ID you want to restore
PATCH {{BASE_URL}}/users/{{USER_ID}}/recover
Authorization: Bearer {{TOKEN}}


### Update user data
# Replace 'userId' with the actual user ID you want to restore
PUT {{BASE_URL}}/users/{{USER_ID}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Jaume",
  "email": "jaume@email.com",
  "password": "jaume"
}


### Create a post
POST {{BASE_URL}}/posts/create
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "Hola mundo!",
  "content": "Hola mundo, me llamo Jaume Blanco González"
}


### Update a post
PUT {{BASE_URL}}/posts/{{POST_ID}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "EDITADO"
}


### Delete a post
DELETE {{BASE_URL}}/posts/{{POST_ID}}
Authorization: Bearer {{TOKEN}}


### Recover a post
PATCH {{BASE_URL}}/posts/{{POST_ID}}/recover
Authorization: Bearer {{TOKEN}}


### Get all non-deleted posts
GET {{BASE_URL}}/posts
Authorization: Bearer {{TOKEN}}


### Get all non-deleted posts of an user by ID
GET {{BASE_URL}}/posts/user
Authorization: Bearer {{TOKEN}}


### Get all deleted posts of an user by ID
GET {{BASE_URL}}/posts/user/deleted
Authorization: Bearer {{TOKEN}}


### Get a post
GET {{BASE_URL}}/posts/{{POST_ID}}
Authorization: Bearer {{TOKEN}}


### Like a post
POST {{BASE_URL}}/posts/{{POST_ID}}/like
Authorization: Bearer {{TOKEN}}


### Determine a post popularity
GET {{BASE_URL}}/posts/{{POST_ID}}/popularity
Authorization: Bearer {{TOKEN}}


### Return user data
GET {{BASE_URL}}/users/{{USER_ID}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json